name: Test workflow 

on:
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: jtmcdole/setup-flutter@7b4ed21124cb564b4e8f1910a17233c8ea152010

      - name: Checkout code
        uses: actions/checkout@v4

      - name: tests
        run: |
          flutter --version
          flutter docotor

