name: Test workflow 

on:
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: jtmcdole/setup-flutter@b07df93ca22c64015c079fc521b5c803ddc48a3a

      - name: Checkout code
        uses: actions/checkout@v4

      - name: tests
        run: |
          flutter --version
          flutter docotor

