name: Test workflow 

on:
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: jtmcdole/setup-flutter@28e495452e033cc15b75f00e638f64b4c6358b0f

      - name: Checkout code
        uses: actions/checkout@v4

      - name: tests
        run: |
          flutter --version
          flutter docotor

